/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_upserve_uppend_blobs_NativeIO */

#ifndef _Included_com_upserve_uppend_blobs_NativeIO
#define _Included_com_upserve_uppend_blobs_NativeIO
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_upserve_uppend_blobs_NativeIO
 * Method:    madvise
 * Signature: (Ljava/nio/MappedByteBuffer;Lcom/upserve/uppend/blobs/NativeIO/Advice;)V
 */
JNIEXPORT void JNICALL Java_com_upserve_uppend_blobs_NativeIO_madvise
  (JNIEnv *, jclass, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
